<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>audio_mixer</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>appicon.ico</ApplicationIcon>
    <Version>0.1.1</Version>
    <AssemblyVersion>0.1.1.0</AssemblyVersion>
    <FileVersion>0.1.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="audio-mixer.Tests/**" />
    <None Remove="audio-mixer.Tests/**" />
    <EmbeddedResource Remove="audio-mixer.Tests/**" />
    <Page Remove="audio-mixer.Tests/**" />
  </ItemGroup>

</Project>

